schema: workflow/2022.04
name: "[TechOps] QA 확인 요청"
settings:
  error_notification: true
triggers:
- id: hi_gKHDy2M
steps:
- namespace: node
  runtime: nodejs18.x
  uses: "./node/entry.js"
- namespace: send_message_public_channel
  runtime: nodejs18.x
  uses: slack-send-message-public-channel@0.2.15
  props:
    slack:
      authProvisionId: apn_wGhl41x
    as_user: true
    conversation: "{{steps.node.$return_value}}"
    text: ":point_right: <https://carpenstreet.atlassian.net/browse/{{steps.trigger.event.body.issue.key}}|Ready
      for QA> 로 상태가 변경되었습니다. <@S057FTKA08J> 확인 부탁드려요 :meowparty:"

